ARG NODE_VERSION=26-alpine-dev

FROM dhi.io/node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
  corepack enable pnpm && pnpm install --dangerously-allow-all-builds --frozen-lockfile; 

COPY . .

ENV WATCHPACK_POLLING=true
ENV HOSTNAME="0.0.0.0"
ENV CI=true

RUN chown -R node:node /app
USER node

EXPOSE 3000

CMD ["sh", "-c", "pnpm dev"]