import type { Metadata } from "next";
import "./globals.css";
import {Space_Mono} from 'next/font/google'

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className={`${spaceMono.className} antialiased min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
